# Generated by Code Haven — AWS ECS Fargate Deployment

terraform {
  required_version = ">= 1.5"
  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

module "service" {
  source = "./module"

  service_name       = var.service_name
  region             = var.region
  vpc_id             = var.vpc_id
  subnet_ids         = var.subnet_ids
  image              = var.image
  port               = var.port
  cpu                = var.cpu
  memory             = var.memory
  min_instances      = var.min_instances
  max_instances      = var.max_instances
  expose             = var.expose
  env_vars           = var.env_vars
  health_check_path  = var.health_check_path
  execution_role_arn = var.execution_role_arn
  task_role_arn      = var.task_role_arn
  tags               = var.tags
}

variable "service_name"       { type = string }
variable "region"             { type = string }
variable "vpc_id"             { type = string }
variable "subnet_ids"         { type = list(string) }
variable "image"              { type = string }
variable "port"               { type = number }
variable "cpu"                { type = number }
variable "memory"             { type = number }
variable "min_instances"      { type = number }
variable "max_instances"      { type = number }
variable "expose"             { type = string }
variable "env_vars"           { type = map(string) }
variable "health_check_path"  { type = string }
variable "execution_role_arn" { type = string }
variable "task_role_arn"      { type = string }
variable "tags"               { type = map(string) }

output "url"                 { value = module.service.url }
output "service_name"        { value = module.service.service_name }
output "cluster_name"        { value = module.service.cluster_name }
output "task_definition_arn" { value = module.service.task_definition_arn }
output "log_group"           { value = module.service.log_group }
