# Generated by Code Haven — Azure Container Apps Deployment

terraform {
  required_version = ">= 1.5"
  backend "azurerm" {}

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}

module "service" {
  source = "./module"

  service_name               = var.service_name
  resource_group_name        = var.resource_group_name
  location                   = var.location
  image                      = var.image
  port                       = var.port
  cpu                        = var.cpu
  memory                     = var.memory
  min_instances              = var.min_instances
  max_instances              = var.max_instances
  expose                     = var.expose
  env_vars                   = var.env_vars
  health_check_path          = var.health_check_path
  managed_environment_id     = var.managed_environment_id
  log_analytics_workspace_id = var.log_analytics_workspace_id
  tags                       = var.tags
}

variable "service_name"               { type = string }
variable "resource_group_name"        { type = string }
variable "location"                   { type = string }
variable "image"                      { type = string }
variable "port"                       { type = number }
variable "cpu"                        { type = number }
variable "memory"                     { type = string }
variable "min_instances"              { type = number }
variable "max_instances"              { type = number }
variable "expose"                     { type = string }
variable "env_vars"                   { type = map(string) }
variable "health_check_path"          { type = string }
variable "managed_environment_id"     { type = string }
variable "log_analytics_workspace_id" { type = string }
variable "tags"                       { type = map(string) }

output "url"             { value = module.service.url }
output "service_name"    { value = module.service.service_name }
output "latest_revision" { value = module.service.latest_revision }
output "resource_group"  { value = module.service.resource_group }
output "environment_id"  { value = module.service.environment_id }
