# Generated by Code Haven — GCP Cloud Run Job (Worker / CronJob)

terraform {
  required_version = ">= 1.5"
  backend "gcs" {}

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

module "job" {
  source = "./module"

  service_name      = var.service_name
  project_id        = var.project_id
  region            = var.region
  image             = var.image
  cpu               = var.cpu
  memory            = var.memory
  env_vars          = var.env_vars
  service_account   = var.service_account
  vpc_connector     = var.vpc_connector
  timeout_seconds   = var.timeout_seconds
  max_retries       = var.max_retries
  parallelism       = var.parallelism
  task_count        = var.task_count
  schedule          = var.schedule
  schedule_timezone = var.schedule_timezone
  labels            = var.labels
}

variable "service_name"      { type = string }
variable "project_id"        { type = string }
variable "region"            { type = string }
variable "image"             { type = string }
variable "cpu"               { type = string }
variable "memory"            { type = string }
variable "env_vars"          { type = map(string) }
variable "service_account"   { type = string }
variable "vpc_connector"     { type = string }
variable "timeout_seconds"   { type = number }
variable "max_retries"       { type = number }
variable "parallelism"       { type = number }
variable "task_count"        { type = number }
variable "schedule"          { type = string }
variable "schedule_timezone" { type = string }
variable "labels"            { type = map(string) }

output "job_name"       { value = module.job.job_name }
output "job_id"         { value = module.job.job_id }
output "project"        { value = module.job.project }
output "region"         { value = module.job.region }
output "scheduler_name" { value = module.job.scheduler_name }
output "schedule"       { value = module.job.schedule }
