# Generated by Code Haven — Intent-Based Deployment
# DO NOT EDIT — regenerated on every pipeline run

terraform {
  required_version = ">= 1.5"

  backend "gcs" {}

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

module "service" {
  source = "./module"

  service_name      = var.service_name
  project_id        = var.project_id
  region            = var.region
  image             = var.image
  port              = var.port
  cpu               = var.cpu
  memory            = var.memory
  min_instances     = var.min_instances
  max_instances     = var.max_instances
  expose            = var.expose
  env_vars          = var.env_vars
  health_check_path = var.health_check_path
  service_account   = var.service_account
  timeout_seconds   = var.timeout_seconds
  concurrency       = var.concurrency
  vpc_connector     = var.vpc_connector
  labels            = var.labels
}

# ── Variables (values provided via terraform.auto.tfvars.json) ──

variable "service_name"      { type = string }
variable "project_id"        { type = string }
variable "region"            { type = string }
variable "image"             { type = string }
variable "port"              { type = number }
variable "cpu"               { type = string }
variable "memory"            { type = string }
variable "min_instances"     { type = number }
variable "max_instances"     { type = number }
variable "expose"            { type = string }
variable "env_vars"          { type = map(string) }
variable "health_check_path" { type = string }
variable "service_account"   { type = string }
variable "timeout_seconds"   { type = number }
variable "concurrency"       { type = number }
variable "vpc_connector"     { type = string }
variable "labels"            { type = map(string) }

# ── Outputs ──

output "url"             { value = module.service.url }
output "service_name"    { value = module.service.service_name }
output "region"          { value = module.service.region }
output "project"         { value = module.service.project }
output "latest_revision" { value = module.service.latest_revision }
