# Generated by Code Haven — GCP GKE (Kubernetes) Deployment

terraform {
  required_version = ">= 1.5"
  backend "gcs" {}

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.0"
    }
  }
}

module "service" {
  source = "./module"

  service_name      = var.service_name
  project_id        = var.project_id
  region            = var.region
  cluster_name      = var.cluster_name
  namespace         = var.namespace
  image             = var.image
  port              = var.port
  cpu               = var.cpu
  memory            = var.memory
  min_instances     = var.min_instances
  max_instances     = var.max_instances
  expose            = var.expose
  env_vars          = var.env_vars
  health_check_path = var.health_check_path
  service_account   = var.service_account
  labels            = var.labels
}

variable "service_name"      { type = string }
variable "project_id"        { type = string }
variable "region"            { type = string }
variable "cluster_name"      { type = string }
variable "namespace"         { type = string }
variable "image"             { type = string }
variable "port"              { type = number }
variable "cpu"               { type = string }
variable "memory"            { type = string }
variable "min_instances"     { type = number }
variable "max_instances"     { type = number }
variable "expose"            { type = string }
variable "env_vars"          { type = map(string) }
variable "health_check_path" { type = string }
variable "service_account"   { type = string }
variable "labels"            { type = map(string) }

output "url"          { value = module.service.url }
output "service_name" { value = module.service.service_name }
output "namespace"    { value = module.service.namespace }
output "cluster_name" { value = module.service.cluster_name }
output "revision"     { value = module.service.revision }
