# Generated by Code Haven — GCP Compute Engine VM Deployment

terraform {
  required_version = ">= 1.5"
  backend "gcs" {}

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

module "service" {
  source = "./module"

  service_name      = var.service_name
  project_id        = var.project_id
  region            = var.region
  zone              = var.zone
  image             = var.image
  port              = var.port
  machine_type      = var.machine_type
  expose            = var.expose
  env_vars          = var.env_vars
  health_check_path = var.health_check_path
  service_account   = var.service_account
  network           = var.network
  subnetwork        = var.subnetwork
  disk_size_gb      = var.disk_size_gb
  labels            = var.labels
}

variable "service_name"      { type = string }
variable "project_id"        { type = string }
variable "region"            { type = string }
variable "zone"              { type = string }
variable "image"             { type = string }
variable "port"              { type = number }
variable "machine_type"      { type = string }
variable "expose"            { type = string }
variable "env_vars"          { type = map(string) }
variable "health_check_path" { type = string }
variable "service_account"   { type = string }
variable "network"           { type = string }
variable "subnetwork"        { type = string }
variable "disk_size_gb"      { type = number }
variable "labels"            { type = map(string) }

output "url"          { value = module.service.url }
output "service_name" { value = module.service.service_name }
output "zone"         { value = module.service.zone }
output "internal_ip"  { value = module.service.internal_ip }
output "project"      { value = module.service.project }
