{{- if .Values.serviceAccount.gcpEmail }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    managed-by: code-haven
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpEmail }}
{{- end }}
